### PR TITLE
Added ability to filter by level to leaderboard controller

### PR DESCRIPTION
**Pull request by JakeLunn**
For Issue #3, added the ability to view high scores per level (including first level). Instead of having an additional page for just the first level, I opted to just add a page that could accept the value for any level.

### CODE REVIEW

**Comment by akatakritos** [comment]
Thanks for this PR! I think the change is great. It looks good,, it follows existing style and patterns, and it even added some validations.

Can you make the change I suggested to pull out a sccore table partial? I think that partial will wind up being useful in other future leaderboards.

**Comment by JakeLunn** [comment]
That's a good idea. I'll do that.

**Comment by akatakritos** [comment]
Thanks @JakeLunn! this is merged and deployed to production. I added your contact info to the footer. Let me know if you want anything else displayed down there or changed in any way,

**Comment by JakeLunn** [comment]
That's awesome, thank you!

**Pull request merged**
